# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    python -m pip install jira
    
  displayName: 'Installing jira'
- script: |
    python test.py $(username) $(password) $(DriverName) $(Summary) $(ReleaseVersion) $(Platforms) $(Customers)
    echo See https://aka.ms/yaml
  displayName: 'Create CONMAP script'
